// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memories.proto

/*
Package memories is a generated protocol buffer package.

It is generated from these files:
	memories.proto

It has these top-level messages:
	GetMemoriesRequest
	GetMemoriesResponse
	GetMemoriesStreamResponse
*/
package memories

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMemoriesRequest struct {
}

func (m *GetMemoriesRequest) Reset()                    { *m = GetMemoriesRequest{} }
func (m *GetMemoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMemoriesRequest) ProtoMessage()               {}
func (*GetMemoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetMemoriesResponse struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *GetMemoriesResponse) Reset()                    { *m = GetMemoriesResponse{} }
func (m *GetMemoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMemoriesResponse) ProtoMessage()               {}
func (*GetMemoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetMemoriesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type GetMemoriesStreamResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetMemoriesStreamResponse) Reset()                    { *m = GetMemoriesStreamResponse{} }
func (m *GetMemoriesStreamResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMemoriesStreamResponse) ProtoMessage()               {}
func (*GetMemoriesStreamResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetMemoriesStreamResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMemoriesRequest)(nil), "GetMemoriesRequest")
	proto.RegisterType((*GetMemoriesResponse)(nil), "GetMemoriesResponse")
	proto.RegisterType((*GetMemoriesStreamResponse)(nil), "GetMemoriesStreamResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Memories service

type MemoriesClient interface {
	GetMemories(ctx context.Context, in *GetMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error)
	GetMemoriesStream(ctx context.Context, in *GetMemoriesRequest, opts ...grpc.CallOption) (Memories_GetMemoriesStreamClient, error)
}

type memoriesClient struct {
	cc *grpc.ClientConn
}

func NewMemoriesClient(cc *grpc.ClientConn) MemoriesClient {
	return &memoriesClient{cc}
}

func (c *memoriesClient) GetMemories(ctx context.Context, in *GetMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error) {
	out := new(GetMemoriesResponse)
	err := grpc.Invoke(ctx, "/Memories/GetMemories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoriesClient) GetMemoriesStream(ctx context.Context, in *GetMemoriesRequest, opts ...grpc.CallOption) (Memories_GetMemoriesStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Memories_serviceDesc.Streams[0], c.cc, "/Memories/GetMemoriesStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &memoriesGetMemoriesStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Memories_GetMemoriesStreamClient interface {
	Recv() (*GetMemoriesStreamResponse, error)
	grpc.ClientStream
}

type memoriesGetMemoriesStreamClient struct {
	grpc.ClientStream
}

func (x *memoriesGetMemoriesStreamClient) Recv() (*GetMemoriesStreamResponse, error) {
	m := new(GetMemoriesStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Memories service

type MemoriesServer interface {
	GetMemories(context.Context, *GetMemoriesRequest) (*GetMemoriesResponse, error)
	GetMemoriesStream(*GetMemoriesRequest, Memories_GetMemoriesStreamServer) error
}

func RegisterMemoriesServer(s *grpc.Server, srv MemoriesServer) {
	s.RegisterService(&_Memories_serviceDesc, srv)
}

func _Memories_GetMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoriesServer).GetMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Memories/GetMemories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoriesServer).GetMemories(ctx, req.(*GetMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memories_GetMemoriesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMemoriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MemoriesServer).GetMemoriesStream(m, &memoriesGetMemoriesStreamServer{stream})
}

type Memories_GetMemoriesStreamServer interface {
	Send(*GetMemoriesStreamResponse) error
	grpc.ServerStream
}

type memoriesGetMemoriesStreamServer struct {
	grpc.ServerStream
}

func (x *memoriesGetMemoriesStreamServer) Send(m *GetMemoriesStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Memories_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Memories",
	HandlerType: (*MemoriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMemories",
			Handler:    _Memories_GetMemories_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMemoriesStream",
			Handler:       _Memories_GetMemoriesStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "memories.proto",
}

func init() { proto.RegisterFile("memories.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0xcd, 0xcd,
	0x2f, 0xca, 0x4c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe1, 0x12, 0x72, 0x4f,
	0x2d, 0xf1, 0x85, 0x0a, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x69, 0x73, 0x09, 0xa3,
	0x88, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0xe6, 0x25, 0xe6, 0xa6, 0x16,
	0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0x41, 0x38, 0x4a, 0xfa, 0x5c, 0x92, 0x48, 0x8a, 0x83,
	0x4b, 0x8a, 0x52, 0x13, 0x73, 0xe1, 0x5a, 0x84, 0xb8, 0x58, 0x40, 0xaa, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0xa3, 0x09, 0x8c, 0x5c, 0x1c, 0x30, 0xe5, 0x42, 0x56, 0x5c, 0xdc,
	0x48, 0xba, 0x85, 0x84, 0xf5, 0x30, 0x9d, 0x23, 0x25, 0xa2, 0x87, 0xc5, 0x35, 0x4a, 0x0c, 0x42,
	0x1e, 0x5c, 0x82, 0x18, 0x36, 0x63, 0x37, 0x41, 0x4a, 0x0f, 0xa7, 0x13, 0x95, 0x18, 0x0c, 0x18,
	0x93, 0xd8, 0xc0, 0xa1, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x7b, 0x36, 0x6b, 0x1f,
	0x01, 0x00, 0x00,
}
